"""Add soft delete flags

Revision ID: 343946d835ab
Revises: ba175e113614
Create Date: 2026-07-03 14:52:43.181972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '343946d835ab'
down_revision: Union[str, None] = 'ba175e113614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_customers_is_deleted'), 'customers', ['is_deleted'], unique=False)
    op.add_column('organization_faqs', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_organization_faqs_is_deleted'), 'organization_faqs', ['is_deleted'], unique=False)
    op.add_column('services', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_services_is_deleted'), 'services', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_is_deleted'), table_name='services')
    op.drop_column('services', 'is_deleted')
    op.drop_index(op.f('ix_organization_faqs_is_deleted'), table_name='organization_faqs')
    op.drop_column('organization_faqs', 'is_deleted')
    op.drop_index(op.f('ix_customers_is_deleted'), table_name='customers')
    op.drop_column('customers', 'is_deleted')
    # ### end Alembic commands ###
