"""Add scheduling edge cases

Revision ID: 3757e35cbdfe
Revises: e26c6be982d4
Create Date: 2026-07-04 12:49:16.798321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3757e35cbdfe'
down_revision: Union[str, None] = 'e26c6be982d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_holidays_date'), 'organization_holidays', ['date'], unique=False)
    op.create_index(op.f('ix_organization_holidays_id'), 'organization_holidays', ['id'], unique=False)
    op.add_column('providers', sa.Column('break_start', sa.Time(), nullable=True))
    op.add_column('providers', sa.Column('break_end', sa.Time(), nullable=True))
    op.add_column('services', sa.Column('buffer_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'buffer_minutes')
    op.drop_column('providers', 'break_end')
    op.drop_column('providers', 'break_start')
    op.drop_index(op.f('ix_organization_holidays_id'), table_name='organization_holidays')
    op.drop_index(op.f('ix_organization_holidays_date'), table_name='organization_holidays')
    op.drop_table('organization_holidays')
    # ### end Alembic commands ###
