"""Add OrganizationUsage table for Dodo Payments

Revision ID: 4d593d92a864
Revises: 27f4ee0a57d9
Create Date: 2026-07-03 22:19:39.276904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d593d92a864'
down_revision: Union[str, None] = '27f4ee0a57d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('vapi_minutes_used', sa.Integer(), nullable=True),
    sa.Column('billing_cycle_start', sa.DateTime(), nullable=True),
    sa.Column('is_active_subscription', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_index(op.f('ix_organization_usage_id'), 'organization_usage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_usage_id'), table_name='organization_usage')
    op.drop_table('organization_usage')
    # ### end Alembic commands ###
