"""Add multi-tenant customer isolation

Revision ID: 67ab8794f729
Revises: 3757e35cbdfe
Create Date: 2026-07-04 13:14:22.204354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ab8794f729'
down_revision: Union[str, None] = '3757e35cbdfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.drop_index('ix_customers_phone', table_name='customers')
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_unique_constraint('uix_org_phone', 'customers', ['organization_id', 'phone'])
    op.create_foreign_key(None, 'customers', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint('uix_org_phone', 'customers', type_='unique')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.create_index('ix_customers_phone', 'customers', ['phone'], unique=True)
    op.drop_column('customers', 'organization_id')
    # ### end Alembic commands ###
