"""Database fixes

Revision ID: 75b2e1d97733
Revises: a1b2c3d4e5f6
Create Date: 2026-07-03 02:50:33.155907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b2e1d97733'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_provider_start_time', 'appointments', ['provider_id', 'start_time'])
    op.add_column('customers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('organizations', 'open_time',
               existing_type=sa.VARCHAR(),
               type_=sa.Time(),
               existing_nullable=True,
               postgresql_using="open_time::time")
    op.alter_column('organizations', 'close_time',
               existing_type=sa.VARCHAR(),
               type_=sa.Time(),
               existing_nullable=True,
               postgresql_using="close_time::time")
    op.alter_column('providers', 'open_time',
               existing_type=sa.VARCHAR(),
               type_=sa.Time(),
               existing_nullable=True,
               postgresql_using="open_time::time")
    op.alter_column('providers', 'close_time',
               existing_type=sa.VARCHAR(),
               type_=sa.Time(),
               existing_nullable=True,
               postgresql_using="close_time::time")
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    
    # Commit transaction to run ALTER TYPE
    op.execute("COMMIT")
    op.execute("ALTER TYPE appointmentstatus ADD VALUE IF NOT EXISTS 'confirmed'")
    op.execute("ALTER TYPE appointmentstatus ADD VALUE IF NOT EXISTS 'no_show'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.alter_column('providers', 'close_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('providers', 'open_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('organizations', 'close_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('organizations', 'open_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('customers', 'created_at')
    op.drop_constraint('uix_provider_start_time', 'appointments', type_='unique')
    # ### end Alembic commands ###
