"""Add Twilio subaccounts and integrations

Revision ID: b2ef60a2c4e7
Revises: 7884609813ff
Create Date: 2026-07-04 17:06:41.011850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ef60a2c4e7'
down_revision: Union[str, None] = '7884609813ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('twilio_subaccount_sid', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('twilio_subaccount_auth_token', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('twilio_phone_number_sid', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('integration_type', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('acuity_user_id', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('acuity_api_key', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('boulevard_api_key', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('boulevard_business_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'boulevard_business_id')
    op.drop_column('organizations', 'boulevard_api_key')
    op.drop_column('organizations', 'acuity_api_key')
    op.drop_column('organizations', 'acuity_user_id')
    op.drop_column('organizations', 'integration_type')
    op.drop_column('organizations', 'phone_number')
    op.drop_column('organizations', 'twilio_phone_number_sid')
    op.drop_column('organizations', 'twilio_subaccount_auth_token')
    op.drop_column('organizations', 'twilio_subaccount_sid')
    # ### end Alembic commands ###
