"""Add price to Service

Revision ID: e26c6be982d4
Revises: 4d593d92a864
Create Date: 2026-07-04 12:42:41.911906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e26c6be982d4'
down_revision: Union[str, None] = '4d593d92a864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('google_oauth_access_token', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('google_oauth_refresh_token', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('google_oauth_expires_at', sa.DateTime(), nullable=True))
    op.add_column('organizations', sa.Column('vapi_voice_id', sa.String(), nullable=True))
    op.add_column('services', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'price')
    op.drop_column('organizations', 'vapi_voice_id')
    op.drop_column('organizations', 'google_oauth_expires_at')
    op.drop_column('organizations', 'google_oauth_refresh_token')
    op.drop_column('organizations', 'google_oauth_access_token')
    # ### end Alembic commands ###
